### ISSUE TITLE
PeterB to "own" one morning topic,  one afternoon topic

### ISSUE THREAD

**Issue by pburkholder** [tfitch/automation-tools-bootcamp#15]
Morning:
- git
- vagrant
- chef

Afternoon:
- packer
- docker
- jenkins

**Comment by tfitch** [comment]
Right now I'd like you to own Chef in the morning and pick from Packer or Docker for the afternoon, but I really want to Jenkins of those three.  Also, we'll hopefully have time to also cover Consul because Packer is a short section.  So you can add that to your available afternoon choices @pburkholder.  Lemme know.

**Comment by pburkholder** [comment]
I don't know jack about Packer, so Docker it is.


On Mon, Oct 5, 2015 at 7:48 PM, Tyler Fitch <notifications@github.com>
wrote:

> Right now I'd like you to own Chef in the morning and pick from Packer or
> Docker for the afternoon, but I really want to Jenkins of those three.
> Also, we'll hopefully have time to also cover Consul because Packer is a
> short section. So you can add that to your available afternoon choices
> @pburkholder <https://github.com/pburkholder>. Lemme know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tfitch/automation-tools-bootcamp/issues/15#issuecomment-145700088>
> .
>



-- 

*Peter Burkholder* — Customer Success Engineer

Unavailability/OOO: Sep 24-25, Nov 2-12

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/pburkholder>  Twitter
<http://www.twitter.com/pburkholder>  Cal
<https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK>
endar

*CHEF*

CHEF.IO <http://www.chef.io/>

TM

*chef.io* <http://www.chef.io/>   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by tfitch** [comment]
We did it!
