### ISSUE TITLE
Create Slack channel for Automation Tools Bootcamp

### ISSUE THREAD

**Issue by tfitch** [tfitch/automation-tools-bootcamp#16]
When attending anyone can join.

And make some hooks between tools in the class and notifications sent to Slack.

**Comment by tfitch** [comment]
Done and invite sent to Peter. https://automationtools.slack.com

**Comment by pburkholder** [comment]
Clarification: Using hangops.slack.com, channel #automationtools_lisa

Signups at http://signup.hangops.com/
